language: generic # default to ruby
sudo: required

services:
    - docker

script:
    - docker run -v $(pwd):/root/.config/nvim autozimu/languageclientneovim bash -c "cd /root/.config/nvim/rplugin/python3 && make"
